# -*- mode: ruby -*-
# vi: set ft=ruby :

if ! File.exists?("resources/Setup_KkmServer.msi")
  puts "KkmServer installer not found"
  exit 1
end

if ! File.exists?("resources/SettingsServ.ini")
  puts "KkmServer settings file not found"
  exit 1
end

Vagrant.configure("2") do |config|

  config.vm.box = "mwrock/Windows2012R2"

  config.vm.network "forwarded_port", guest: 5893, host: 5893, protocol: "tcp"

  config.vm.provision :shell, path: "scripts/install-kkmserver.cmd"

end
