# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.trigger.before :up do

    unless File.exists?("resources/Setup_KkmServer.exe")
      puts "KkmServer installer not found"
      exit 1
    end

    unless File.exists?("resources/SettingsServ.ini")
      puts "KkmServer settings file not found"
      exit 1
    end

  end

  config.vm.box = "jacqinthebox/windowsserver2016"

  config.vm.network "forwarded_port", guest: 5893, host: 5893, protocol: "tcp"
  config.vm.network "forwarded_port", guest: 3389, host: 2200, protocol: "tcp"

  config.vm.provision :shell, path: "scripts/set-timezone.cmd"
  config.vm.provision :shell, path: "scripts/install-kkmserver.cmd"

end
